name: Java CI with Gradle

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Обновите версию, указав актуальный тег или хэш
          ref: v2.4.2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Start SUT
        run: java -jar ./artifacts/app-card-delivery.jar &

      - name: Build and test with Gradle
        run: ./gradlew test

      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: build/test-results

      - name: Archive screenshots on failure
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: build/reports/tests/failed

      - name: Stop SUT
        run: pkill -f 'java -jar ./artifacts/app-card-delivery.jar'


